Dark / Light theme documentation
flowershow/flowershow pull request #106
Opened 2022-08-18 18:29 UTC by khalilcodes

## Documentation for dark and light theme modes
#56 
***
This PR adds user and developer documentation for dark/light mode usage or modification.

### Tasks
- [x] Add documentation @ [/docs/theme]()

2022-08-19 11:21 UTC, olayway requested changes

2022-08-19 11:21 UTC, olayway commented on site/content/docs/theme.md
> +![[dark-theme.jpg]]
see my comment to #107 re images

2022-08-25 06:02 UTC, khalilcodes commented
@olayway I have updated the docs with the changes specified

2022-08-25 13:53 UTC, olayway commented on site/content/docs/theme.md
> +The theme switcher button can be found in `templates/default/components/ThemeSelector.js` file. There you can find the button's icon (svg) and can replace or modify it as per your need.
Ahhh yes, I see what you mean. In this case, let's maybe just use a default one for now and don't allow for customizing it? I think it is really minor and the icon you chose is really nice.

2022-08-25 14:04 UTC, olayway approved these changes
Thank you @khalilcodes! This is ready to go!

2022-08-25 15:40 UTC, merged