Callouts fix and documentation
flowershow/flowershow pull request #251
Opened 2022-11-04 13:07 UTC by khalilcodes

### Summary
***
Resolves #243 

This PR updates the callouts plugin and it's documentation.

### Changes
***
* Bump remark-callouts `v1.0.1 --> v1.0.2` which contains fix for case insensitive match eg. `> [!TIP]`
* Move callouts docs from [docs/syntax](https://flowershow.app/docs/syntax) to [docs/callouts]()
  - Add documentation for supported types

2022-11-05 08:15 UTC, rufuspollock requested changes
Small tweaks to docs.

2022-11-05 08:15 UTC, rufuspollock commented on site/content/docs/callouts.md
> +**Example:**
Can we use headings rather than bold e.g. `##` here.

2022-11-05 08:15 UTC, rufuspollock commented on site/content/docs/callouts.md
> +**Supported Types:**
Also a heading e.g. h2

2022-11-05 08:15 UTC, rufuspollock commented on site/content/docs/callouts.md
> +<div className="border-2 border-slate-400 rounded-md px-4 my-4">
Couldn't this be an info callout now 🙂 (let's avoid custom html wherever possible as it goes out of sync fast)

2022-11-05 08:15 UTC, rufuspollock commented on site/content/docs/callouts.md
> +**Renders as:**
This is bold not a heading (although not sure bolding is actually needed)

2022-11-05 08:34 UTC, rufuspollock commented
Other point: there's no test here. I think that is ok because a downstream plugin but in that case should be a test in `remark-callouts` and i don't see that https://github.com/flowershow/remark-callouts/commit/5e8474fafcd5626611181fc17f4023e513e5edbb#commitcomment-88951619

2022-11-05 19:17 UTC, khalilcodes commented
@rufuspollock docs updated with changes and test added in remark-callouts 👍

2022-11-08 10:45 UTC, rufuspollock commented on templates/default/package.json
> +    "remark-callouts": "^1.0.2",
As a very minor comment i think `remark-callouts` should have bumped at least a minor version e.g. `1.1.0` for what is a substantive change / fix.

2022-11-08 10:45 UTC, merged

2022-11-08 10:46 UTC, rufuspollock commented
@khalilcodes LGTM and took liberty of merging prior to meeting.