Blog layout component and blog authors
flowershow/flowershow pull request #339
Opened 2022-12-02 14:24 UTC by PhilippeduPreez

## Changes

- added `blog` layout component
- added `authors` type in contentlayer

## Notes
- Currently a default author will be given to all pages, if we only want eg. blog posts to receive author data as props, we could use a conditional in `[[...slug]].jsx` to only do this for blog posts
- closes #239

2022-12-05 08:46 UTC, olayway commented
@PhilippeduPreez can you please check why the checks are failing? :)

2022-12-05 17:13 UTC, olayway requested changes
Please take a look at my comments and let me know if you need some clarification.
Apart from the required changes there are also authors missing in the blogs list.

2022-12-05 17:13 UTC, olayway commented on packages/template/contentlayer.config.js
> +  },
You don't need to create another computed field just to find a specific author. You can just use his name.

2022-12-05 17:13 UTC, olayway commented on packages/template/contentlayer.config.js
> +      type: "string",
This should have a default value. And while I like the one you picked, let's use that boring gray and white icon with the shape of the head 😅

2022-12-05 17:13 UTC, olayway commented on site/content/authors/default.mdx
> +---
You can define default values for contentlayer document type fields, like we do e.g. here `layout: { type: "string", default: "blog" }` 😜

2022-12-05 22:27 UTC, PhilippeduPreez commented
@olayway >there are also authors missing in the blogs list. If you mean the blog index page, I didn't see authors in the examples we drew inspiration from, so only displayed them in the actual blog post

2022-12-06 18:38 UTC, olayway commented
After a looong debugging I've managed to make the tests from the `blog.spec` pass. It seems that when there is no `search` property set in the user config blog pages will show the following error, but no idea why only on blog pages... I'll continue working on it tomorrow morning.

![image](https://user-images.githubusercontent.com/52197250/205994210-e954a550-93b3-480a-aa02-27bdd214aba5.png)

2022-12-07 09:23 UTC, olayway commented
> After a looong debugging I've managed to make the tests from the `blog.spec` pass. It seems that when there is no `search` property set in the user config blog pages will show the following error, but no idea why only on blog pages... I'll continue working on it tomorrow morning.

It seems this is somehow related to `blog` layout and importing `allAuthors` from contentlayer, as replacing the import with just `const allAuthors = []` seems to "fix" the issue. But I have no idea why and how these two things are related...

2022-12-09 01:16 UTC, closed without merging