Page comments / discussions
flowershow/flowershow pull request #406
Opened 2023-01-30 11:02 UTC by khalilcodes

Tasks from #163 
### Summary

This PR adds the feature to enable comments on pages by setting up in config and/or frontmatter.

### Changes
* Create comments components in core for [giscus](https://giscus.app/) and [utterances](https://utteranc.es/)
  * Add giscus react package in core 
* Add configs in frontmatter and config.js

### TODO
- [ ] Create documentation
- [ ] Add `env.example`
- [ ] install giscus app in flowershow repo

### Screenshot (giscus comments)
<img width="1429" alt="Screen Shot 2023-01-30 at 1 35 11 PM" src="https://user-images.githubusercontent.com/42637597/215459613-e3122d76-6d2f-4031-8684-fa81e33286de.png">

2023-01-31 19:31 UTC, olayway requested changes
Good job @khalilcodes! But there are a few things I'd do differently 😋

2023-01-31 19:31 UTC, olayway commented on packages/core/src/ui/Comments/index.tsx
> + */
Some old comment?

```suggestion
```

2023-01-31 19:31 UTC, olayway commented on packages/core/src/ui/Comments/index.tsx
> +}
Comment out or remove?

2023-01-31 19:31 UTC, olayway commented on packages/core/src/ui/Comments/Utterances.tsx
> +    issueTerm?: string;
I'm guessing `theme` and `issueTerm` could be of more strict types, e.g. `theme: "light" | "dark"`?

2023-01-31 19:31 UTC, olayway commented on packages/core/src/ui/Comments/Utterances.tsx
> +    script.setAttribute("theme", commentsTheme as string);
So are these values always defined? In this case in the interface they shouldn't have `?` signs next to their names.

2023-01-31 22:49 UTC, khalilcodes commented on packages/core/package.json
> +    }
forgot to remove 😅

2023-01-31 23:00 UTC, khalilcodes commented
@olayway for a new feat would this be a minor version bump or keep it as patch ?

2023-02-01 11:57 UTC, olayway approved these changes
LGTM :) If everything works and you've tested each provider, then I think we can merge!

2023-02-01 12:09 UTC, olayway commented
> @olayway for a new feat would this be a minor version bump or keep it as patch ?

Definitely a minor bump 😃

2023-02-01 12:18 UTC, olayway commented on .changeset/silver-buses-tap.md
> +"@flowershow/core": patch
Let's make it a "minor" change

2023-02-01 18:52 UTC, merged

2023-02-02 21:03 UTC, rufuspollock commented
@khalilcodes @olayway great work everyone 👏 

2 quick small comments:

- docs page naming: why `page-comments` vs `comments`? `comments` seems simpler and i assume this applies to blog pages as well etc?
- could we get a `created` date on the page
- shall we turn this docs page into a blog post by adding `type: Blog` (seems worth of it!)
- have we turned this on for the site? if so where can i try it out?