Add obsidian canvas support
flowershow/flowershow pull request #629
Opened 2024-02-02 04:19 UTC by mohamedsalem401

For https://github.com/datopian/flowershow/issues/578
Supported:
- PDF 
- Youtube embeds
- Images
- Text
- Edges 
- Embedded markdown files

2024-02-07 18:50 UTC, olayway requested changes
This is amazing! There are some minor fixes needed though, like:
1) Hiding the overflowing content
2) Hiding `#` next to headings
3) Arrows should be ended with arrows, not circles
3) (Minor) Add links to names of embedded files

![image](https://github.com/datopian/flowershow/assets/52197250/881fe2ab-c535-4e36-abc8-0b4bccbfde0f)

Also, we need to adjust the main layout so that we can go full width, but let's create a separate issue for that. And another one for zoom/pinch controls.

2024-03-26 08:05 UTC, saviorand commented
Very impressive!

2024-06-01 20:36 UTC, rufuspollock commented
@olayway could we merge this? Is it "good enough for now"?

2025-04-09 19:46 UTC, nosovk commented
Would be nice to get that onboard

2025-05-20 09:34 UTC, closed without merging