SEO Documentation page
flowershow/flowershow pull request #80
Opened 2022-08-08 22:15 UTC by khalilcodes

## SEO Docs
Task from #79 
***

This PR adds the SEO documentation page in docs -

2022-08-09 13:12 UTC, rufuspollock requested changes
The idea was to *just* have the documentation - not the rest of the stuff and then we add that once the docs are clear.

2022-08-09 13:13 UTC, rufuspollock commented on site/content/docs/seo.md
> +Flowershow uses the [NextSeo]( https://github.com/garmeeh/next-seo) plugin that helps to add seo properties to the page and is a fairly easy setup to follow.
seo should be capitalized

2022-08-09 13:15 UTC, rufuspollock commented on site/content/docs/seo.md
> +
Brief explanation of what we mean by SEO: e.g. 

Flowershow supports adding standard metadata to your pages to improve social media sharing and search engine discovery.

As well as setting values for individual pages you can add a default image and description that will be used on pages without this set.

2022-08-09 13:15 UTC, rufuspollock commented on site/content/docs/seo.md
> +Note: It is advised to upload an image with the same width and height values as specified above for it to display properly.
Add some info about what the result will be e.g. "When sharing on twitter you will get a result like this"

2022-08-10 09:38 UTC, khalilcodes commented
I hadn't realized that the commits from the other branch were included here too. I will close this PR and open a clean one with the mentioned updates (as I think this will eventually lead to future merge conflicts).

2022-08-10 09:40 UTC, closed without merging